include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - "lib/generated/**"
    - "**.freezed.dart"
    - "**.g.dart"
    - "lib/injection.config.dart"
    
  errors:
    invalid_annotation_target: ignore