name: railways
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  dio: ^4.0.6
  very_good_analysis: ^3.1.0
  logger: ^1.1.0
  go_router: ^5.2.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  flutter_stripe: ^7.0.0
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.3.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
