# Generated by Django 4.1.3 on 2022-11-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='arrival_points',
        ),
    ]
